#ifndef ERROR_H_
#define ERROR_H_

#define BAD_INDEX_TYPE 0
#define BAD_INITIALIZATION 1
#define BAD_STORAGE 2
#define BAD_OPERATION 3
#define EMPTY 4
#define INVALID_ARGUMENT 5
#define INVALID_ADVERB_ARGUMENT 6
#define OUT_OF_BOUNDS 7
#define SHAPE_MISMATCH 8
#define TEST_ERROR 9
#define UNSUPPORTED_OBJECT 10
#define UNSUPPORTED_SUBJECT 11
#define UNKNOWN_KEY 12
#define UNEQUAL_ARRAY_LENGTHS 13
#define DIVISION_BY_ZERO 14
#define MAXIMUM_ITERATIONS 15

#endif